"""Pydantic contracts for tag tools."""

from ._common import (
    TagIdRequest,
    TagSelector,
)

from .inventory import (
    AttachTagToNodeRequest,
    AttachTagToNodeResponse,
    AttachTagToServiceRequest,
    AttachTagToServiceResponse,
    CountTagServicesRequest,
    CountTagsRequest,
    CountTagsResponse,
    CreateTagRequest,
    CreateTagResponse,
    DeleteTagRequest,
    DeleteTagResponse,
    DetachTagFromNodeRequest,
    DetachTagFromNodeResponse,
    DetachTagFromServiceRequest,
    DetachTagFromServiceResponse,
    ListTagsRequest,
    TagFilterRequest,
    TagIdentityRequest,
    TagNodesRequest,
    TagNodesResponse,
    TagServicesRequest,
    TagServicesResponse,
    TagPropsResponse,
    TagRow,
    TagRelationCountResponse,
    TagSelectorRequest,
    TagRowsResponse,
)

__all__ = [
    "AttachTagToNodeRequest",
    "AttachTagToNodeResponse",
    "AttachTagToServiceRequest",
    "AttachTagToServiceResponse",
    "CountTagServicesRequest",
    "CountTagsRequest",
    "CountTagsResponse",
    "CreateTagRequest",
    "CreateTagResponse",
    "TagIdRequest",
    "DeleteTagRequest",
    "DeleteTagResponse",
    "DetachTagFromNodeRequest",
    "DetachTagFromNodeResponse",
    "DetachTagFromServiceRequest",
    "DetachTagFromServiceResponse",
    "ListTagsRequest",
    "TagFilterRequest",
    "TagIdentityRequest",
    "TagNodesRequest",
    "TagNodesResponse",
    "TagServicesRequest",
    "TagServicesResponse",
    "TagPropsResponse",
    "TagRow",
    "TagRelationCountResponse",
    "TagSelector",
    "TagSelectorRequest",
    "TagRowsResponse",
]
