"""Pydantic contracts for array tools."""

from .inventory import (
    ArrayDiskgroupRequest,
    ArrayDiskgroupResponse,
    ArrayDiskgroupsRequest,
    ArrayDiskgroupsResponse,
    ArrayFilterRequest,
    CountArraysRequest,
    CountArraysResponse,
    GetArrayRequest,
    ArrayPropsResponse,
    ArrayProxiesRequest,
    ArrayProxiesResponse,
    ArrayRelationCountRequest,
    ArrayRelationCountResponse,
    ArrayRow,
    ArrayRowsResponse,
    ArrayTargetsRequest,
    ArrayTargetsResponse,
    ListArraysRequest,
)

__all__ = [
    "ArrayDiskgroupRequest",
    "ArrayDiskgroupResponse",
    "ArrayDiskgroupsRequest",
    "ArrayDiskgroupsResponse",
    "ArrayFilterRequest",
    "CountArraysRequest",
    "CountArraysResponse",
    "GetArrayRequest",
    "ArrayPropsResponse",
    "ArrayProxiesRequest",
    "ArrayProxiesResponse",
    "ArrayRelationCountRequest",
    "ArrayRelationCountResponse",
    "ArrayRow",
    "ArrayRowsResponse",
    "ArrayTargetsRequest",
    "ArrayTargetsResponse",
    "ListArraysRequest",
]
