"""Pydantic contracts for array tools."""

from .inventory import (
    ArrayDiskgroupFilterRequest,
    ArrayDiskgroupQuotaRequest,
    ArrayDiskgroupQuotaResponse,
    ArrayDiskgroupQuotasRequest,
    ArrayDiskgroupQuotasResponse,
    ArrayDiskgroupRequest,
    ArrayDiskgroupResponse,
    ArrayDiskgroupRowsResponse,
    ArrayDiskgroupsRequest,
    ArrayDiskgroupsResponse,
    ArrayFilterRequest,
    ArrayPropsResponse,
    ArrayProxiesRequest,
    ArrayProxiesResponse,
    ArrayRelationCountRequest,
    ArrayRelationCountResponse,
    ArrayRow,
    ArrayRowsResponse,
    ArrayTargetsRequest,
    ArrayTargetsResponse,
    CountArraysRequest,
    CountArraysResponse,
    GetArrayRequest,
    ListArrayDiskgroupsRequest,
    ListArraysRequest,
)

__all__ = [
    "ArrayDiskgroupFilterRequest",
    "ArrayDiskgroupQuotaRequest",
    "ArrayDiskgroupQuotaResponse",
    "ArrayDiskgroupQuotasRequest",
    "ArrayDiskgroupQuotasResponse",
    "ArrayDiskgroupRequest",
    "ArrayDiskgroupResponse",
    "ArrayDiskgroupRowsResponse",
    "ArrayDiskgroupsRequest",
    "ArrayDiskgroupsResponse",
    "ArrayFilterRequest",
    "ArrayPropsResponse",
    "ArrayProxiesRequest",
    "ArrayProxiesResponse",
    "ArrayRelationCountRequest",
    "ArrayRelationCountResponse",
    "ArrayRow",
    "ArrayRowsResponse",
    "ArrayTargetsRequest",
    "ArrayTargetsResponse",
    "CountArraysRequest",
    "CountArraysResponse",
    "GetArrayRequest",
    "ListArrayDiskgroupsRequest",
    "ListArraysRequest",
]
