import os


OPENSVC_API_BASE_URL = os.getenv("OPENSVC_API_BASE_URL")
MCP_HOST = os.getenv("MCP_HOST", "127.0.0.1")
MCP_PORT = os.getenv("MCP_PORT", "8011")
MCP_TOOL_SEARCH_MAX_RESULTS = 10

HTTP_REQUEST_TIMEOUT_SECONDS = 20.0
TOOL_TIMEOUT_SECONDS = 90.0
COLLECTOR_FANOUT_MAX_CONCURRENCY = 20
