from pydantic import BaseModel, ConfigDict, Field, model_validator


class ToolConfirmation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    phrase: str = Field(
        description=(
            "Exact confirmation phrase generated by the assistant and repeated "
            "verbatim by the user in the latest message. Required before calling "
            "state-changing MCP tools. The gateway verifies that this phrase is "
            "present in the latest user message before forwarding the tool call."
        ),
        min_length=1,
        examples=["DELETE node NODE-ID lab-node-01"],
    )

    @model_validator(mode="after")
    def normalize(self) -> "ToolConfirmation":
        self.phrase = self.phrase.strip()
        if not self.phrase:
            raise ValueError("confirmation phrase must not be empty")
        return self
